### PR TITLE
Implemented Task 2: added password toggle icon

### PR DESCRIPTION
**Pull request by daibolini**
## Purpose
Adding an eye icon next to password field to let users show or hide the password, making it easier to confirm that they are typing it correctly without compromising security.

## Screenshots
image

image

## Steps for QA
Check default behavior: Password is hidden (default).
Click the eye icon: Password should be visible.
Click again: Password should be hidden again.

### CODE REVIEW

**Comment by jayp-tech** [comment]
Great work Diana, but Can you make sure you do not commit your appsettings.json file for now ?

Ideally Krish has been assigned a task to include this json in .gitignore so that it does not get pushed accidentally like this.

**Comment by jayp-tech** [comment]
Thanks, as a last rule.
You should test your code whether the password toggle works and put some screenshots in the PR. Next you change the label to “ Ready for QA” 

Once the label is ready for QA ideally a tester will test your code ( in this case Me ) and then merge it to main.

**Comment by daibolini** [comment]
ok, note that i fixed my name that had a mispelling so if you pull my request to change the database and try to login with my username it will be daiana instead of diana

**Comment by daibolini** [comment]
I'm not sure if I have permission to change the label

**Pull request merged**
